### ISSUE TITLE
It breaks with more than one chart on the same page

### ISSUE THREAD

**Issue by DougTrajano** [haoda-li/mkdocs-plotly-plugin#1]
Hi buddy! Thank you for this project. Unfortunately, I'm facing an issue with that.

It breaks with more than one chart on the same page. Probably because we are overwriting the data variable.

**Comment by dsingh14usf** [comment]
facing the same issue
Is there any workaround for this?

**Comment by haoda-li** [comment]
> facing the same issue Is there any workaround for this?

Could you provide a more specific failure case?

Note that you should only put one plot within one fence, something like

````
```plotly
{"file_path": "../assets/plot1.json"}
```

```plotly
{"file_path": "../assets/plot2.json"}
```
````

**Comment by dsingh14usf** [comment]
Hi
Having two fences worked for me. Appreciate the prompt response.

Many Thanks!
