### ISSUE TITLE
log x axis is not shown

### ISSUE THREAD

**Issue by legendof-selda** [haoda-li/mkdocs-plotly-plugin#2]
When we export the chart with log x axis, the plugin displays the chart without the log axis.

However, disabling the template `enable_template: false`, you can see the log axis correctly.

I am guessing the templates used changes the x axis.

**Comment by legendof-selda** [comment]
I believe it's because in the template, nested dict is used instead of flat strings and according to Plotly [docs](https://plotly.com/javascript/plotlyjs-function-reference/), when nested dict is provided the enti property is replaced. Having a flattened template dict should solve this.

**Comment by legendof-selda** [comment]
it has been 2 weeks and no update

is this plugin maintained?

**Comment by haoda-li** [comment]
Merged, closing the issue.
